# 数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.2:3306/guili?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # type: com.alibaba.druid.pool.DruidDataSource 数据源
  # 开发环境
  profiles:
    active: dev
  # 返回jackson全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 服务名称 只能使用"-"来连接
  application:
    name: service-order
  # nacos访问地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # redis 配置
  redis:
    host: 192.168.2.2
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        # 最大阻塞等待时间,负数表示没限制
        max-wait: -1
        max-idle: 5
        min-idle: 0

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # xml 文件地址
  mapper-locations: classpath:com/xh/orderService/mapper/xml/*.xml

# 端口号
server:
  port: 8007

# 设置日志级别
logging:
  level:
    # 日志具体实现在哪个报下  mapper包下  debug等级
    com.xh.orderService.mapper: debug
#feign:
 # hystrix:
  #  enabled: true


# 微信登录参数
wx:
  open:
    # 微信开放平台 appid
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirect_url: http://guli.shop/api/ucenter/wx/callback

weixin:
  pay:
    #关联的公众号appid
    appid: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notifyurl: http://guli.shop/api/order/weixinPay/weixinNotify

